# modified from https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/blob/main/.github/workflows/build_local.yml
name: Pure

on:
  workflow_dispatch:

env:
    # this has to be synchronized with the same variable in build_local.sh
    PACKAGE_UPLOAD: ${{ github.workspace }}/upload
    __HACK_1__: ${{ secrets.HACK1 }}

jobs:
  wine-crossover-local:

    strategy:
      fail-fast: false

    runs-on:  macos-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache build
        uses: actions/cache@v3
        with:
          key: build-${{ hashFiles('**/build.sh') }}
          path: |
            build
          restore-keys: |
            build-${{ hashFiles('**/build.sh') }}
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - name: Checkout wine
        uses: actions/checkout@v3
        with:
          repository: 3Shain/winecx
          path: sources/wine
          ref: gi-wine-pure
      # - name: Checkout dxvk
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 3Shain/DXVK-macOS
      #     path: sources/dxvk

      - name: Run build_local.sh
        run: ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-build
          path: ${{ env.PACKAGE_UPLOAD }}